/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
 * ubs-engine is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef IT_FAULT_LOG_HELPER_H
#define IT_FAULT_LOG_HELPER_H

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

namespace ubse::it::infra {

/**
 * @brief Parsed entry from a single [UBSE_MEM] line in ubse_fault.log.
 *
 * Each field corresponds to a key=value pair in the BorrowFailedAdvice output.
 */
struct FaultLogEntry {
    std::string processDesc;   // "Borrow Schedule failed" / "Import failed" / ...
    std::string requestName;   // RequestName=xxx
    std::string borrowType;    // BorrowType=WATER_BORROW / APP_NUMA_BORROW / ...
    uint64_t requestSize = 0;  // RequestSize=xxx (bytes)
    std::string exportNode;    // ExportNode=xxx
    std::string importNode;    // ImportNode=xxx
    std::string requestNode;   // RequestNode=xxx
    std::string masterNode;    // MasterNode=xxx
    std::string errorCode;     // ErrorCode=ubse_borrow_XXXX
    std::string errorInfo;     // ErrorInfo=xxx
    uint32_t adviceCode = 0;   // AdviceCode=xxx
    std::string advice;        // Advice=xxx
};

/**
 * @brief Helper for reading and validating ubse_fault.log content.
 *
 * Provides utilities to read, parse, wait for, and clear the fault log
 * generated by BorrowFailedAdvice().
 */
class ItFaultLogHelper {
public:
    /**
     * @brief Read the entire fault log file as a string.
     *
     * @param faultLogPath Absolute path to ubse_fault.log
     * @return File content, or empty string if file does not exist
     */
    static std::string ReadFaultLog(const std::string& faultLogPath);

    /**
     * @brief Parse a single [UBSE_MEM] log line into a structured FaultLogEntry.
     *
     * @param line A single log line (expected to start with "[UBSE_MEM]")
     * @param entry [out] Parsed entry
     * @return true if parsing succeeded, false otherwise
     */
    static bool ParseFaultLogEntry(const std::string& line, FaultLogEntry& entry);

    /**
     * @brief Parse all [UBSE_MEM] entries from a fault log file.
     *
     * @param faultLogPath Absolute path to ubse_fault.log
     * @return Vector of parsed entries (empty if file does not exist or has no entries)
     */
    static std::vector<FaultLogEntry> ParseAllEntries(const std::string& faultLogPath);

    /**
     * @brief Poll the fault log until a matching entry appears or timeout.
     *
     * Reads the fault log file every @p pollIntervalMs, parsing all [UBSE_MEM]
     * entries and checking each against @p matcher. Returns all matching entries
     * found so far (may include entries from previous polls).
     *
     * @param faultLogPath Absolute path to ubse_fault.log
     * @param matcher Predicate returning true for matching entries
     * @param timeoutMs Maximum wait time in milliseconds (default 10s)
     * @param pollIntervalMs Time between polls in milliseconds (default 500ms)
     * @return All matching entries found (empty if timeout)
     */
    static std::vector<FaultLogEntry> WaitForFaultLog(const std::string& faultLogPath,
                                                      std::function<bool(const FaultLogEntry&)> matcher,
                                                      uint32_t timeoutMs = 10000, uint32_t pollIntervalMs = 500);

    /**
     * @brief Clear (truncate) the fault log file.
     *
     * Useful for resetting state between test cases to avoid interference.
     *
     * @param faultLogPath Absolute path to ubse_fault.log
     */
    static void ClearFaultLog(const std::string& faultLogPath);
};

} // namespace ubse::it::infra

#endif // IT_FAULT_LOG_HELPER_H
