/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 *
 * virtagent is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#ifndef VM_MEM_H
#define VM_MEM_H

#include <sstream>
#include <vector>

namespace vm {
using NodeLocInfo = struct TagUbseNodeLocInfo {
    TagUbseNodeLocInfo() = default;
    std::string hostId{};
    int16_t socketId{};
    int16_t numaId{};

    bool operator==(const TagUbseNodeLocInfo &a) const
    {
        return (hostId == a.hostId && socketId == a.socketId && numaId == a.numaId);
    }

    std::string toString() const
    {
        std::ostringstream oss;
        oss << hostId << "," << socketId << "," << numaId;
        return oss.str();
    }
};

using BorrowItem = struct TagUbseBorrowItem {
    uint16_t exportLocNum{};                  // Number of NUMA nodes providing memory
    std::vector<NodeLocInfo> exportLocInfo{}; // Locations of NUMA nodes providing memory for a single borrow
                                              // operation, at most two NUMA nodes from a single physical node P
    std::vector<uint64_t> requestSize{};      // Amount of memory provided by each NUMA node
    uint64_t exportMemId{};                   // memid generated by OBMM on the exporting node
    uint64_t importMemId{};                   // memid generated by OBMM on the local importing node
    std::string name{};                       // Borrowing account name
};

using BorrowItemInfo = struct TagUbseBorrowItemInfo {
    std::vector<BorrowItem> borrowItem{};
};

using LendItem = struct TagUbseLendItem {
    NodeLocInfo importNumaLoc{}; // Location of the borrowing side
    uint16_t exportLocNum{};     // Actual number of NUMA nodes lending memory for this item; at most two NUMA nodes can
                                 // jointly provide memory in a single lend operation
    std::vector<NodeLocInfo> exportLocInfo{}; // Locations of NUMA nodes providing memory
    uint64_t exportMemId{};                   // OBMM export result (memid) on the local node
    uint64_t importMemId{};                   // OBMM import result (memid) on the borrowing node
    std::vector<uint64_t> requestSize{};      // Amount of memory provided by each NUMA node
};

using LendItemInfo = struct TagUbseLendItemInfo {
    int lendItemNum{}; // Actual number of lending records for this NUMA
    std::vector<LendItem> lendItem{};
};

} // namespace vm
#endif