# Name of the process_mem plugin. Fixed value: process_mem.
ubse.plugin.name=process_mem
# Name of the SO file on which the process_mem module depends. Fixed value: libprocess_mem.so.
ubse.plugin.pkg=libprocess_mem.so

[process_mem.pid]
# NUMA distribution collection interval, in seconds. The value range is [1, 3600]. Any invalid value will be reset to 10.
collect.interval=10
# Timeout threshold for CREATING memory borrow debts, in seconds. If a borrow remains in CREATING state beyond this timeout, the PID is reset. Any invalid value will be reset to 30.
borrow.timeout=10