# virt_agent plugin. Default value: 205
# virt_agent=205
# mempooling plugin. Default value: 777
# mempooling=777
# ucache plugin. Default value: 778
# ucache=778
# mem_plugin plugin. Default value: 779
mem_plugin=779
