[ubse.log]
# Log level. The value can be DEBUG, INFO (default value), WARN, ERROR, or CRIT. Any invalid value will be reset to INFO.
log.level=INFO
# Size of the log file to be wrapped, in MB. The value range is [2, 20]. Any invalid value will be reset to 20.
log.max.fileSize=20
# Maximum number of log files that can be wrapped. The value range is [1, 200]. Any invalid value will be reset to 20.
log.fileNums=20
# Maximum number of logs that can be cached in the log buffer. If the number of cached logs exceeds the value, the earliest logs are overwritten. Value range: [64,4096]. Any invalid value will be reset to 4096.
log.queue.maxItem=4096
# Syslog switch.The value can be true or false(default value). Any invalid value will be reset to false.
log.sys.open=false
# Syslog type.The value can be kern, user(default value), mail, daemon, auth, syslog, lpr, news, uucp, cron, authpriv, ftp, or local0~7. Any invalid value will be reset to user.
log.sys.type=user

[ubse.election]
# Interval at which the Master node sends heartbeat messages, in milliseconds. The value range is from 1000 to 60000. Any invalid value will be reset to 2000.
heartbeat.timeInterval=2000
# Threshold for the number of lost standby node heartbeats. The value ranges from 3 to 20. Any invalid value will default to 3.
heartbeat.lostThreshold=3

[ubse.rpc]
# The timeout for calling the rpc interface, in seconds, the default time is 60s. The value range is from 0 to 65535. Any invalid value will be reset to 60.
request.timeout=60
# When the communication mode is TCP, configure the IP addresses of all nodes within the cluster. Continuous IP address segments are supported, with segments separated by a hyphen (-). Both address segments and individual addresses can coexist, separated by a comma (,).
# cluster.ipList=192.168.100.100-192.168.100.102,192.168.100.104
# Whether to enable TLS certificate authentication
# true: Enable TLS authentication and use certificates for secure communication
# false: Disable TLS authentication, communication will be unencrypted
# Note: This feature can only be enabled under the TCP protocol.
cert.use=false

[ubse.ubfm]
# Port number of the http tcp server. The value range is [1024, 65535]. Any invalid value will be reset to 8082.
ubse.server.port=8082
# Set the Port for Sending Messages to the lcne. The value range is [1024, 65535]. Any value out of range is reset to 34256
# The value must match the lcne listening port.
lcne.server.port=34256

[ubse.memory]
# pool memory ratio of all node, it take effect when there isnot node.pool.memory.ratio configuration, unit is %.
system.pool.memory.ratio = 100
# The default value is 128. If this parameter is set, the value must be greater than 128 MB.
obmm.memory.block.size=128