ubse.plugin.name=ucache
ubse.plugin.pkg=libucache_plugin.so
# export interval
ucache.export.interval=10
# Borrowing strategy unit
strategy.borrow_size=1073741824
# The maximum number of output actions of the borrowing strategy
strategy.maxActionSize=10
# Borrowing strategy balance threshold
strategy.balanceThreshold=1.5
# Borrowing strategy minimum borrowing scarcity
strategy.scarcityThreshold=0.01
# Bottleneck - threshold (type: uint32, unit: kb/s, default：10240 kb/s)
#    min: 1
#    max: 10*1024*1024 (nvme disk read limit)
bottleneck.threshold=10240
# Bottleneck - short window size (type: uint32，unit: second, default: 180)
#    min：30. The window has at least 3 points, calculated based on a 10-second period, and at least 30 seconds.
#    max：1200. ccording to the puncture experience, the PageCache volume reaches its peak in about 20 minutes.
bottleneck.short.size=180
# Bottleneck - short window threshold (type：uint32, unit: percent, default: 70%)
#    min: 0
#    max: 100
bottleneck.short.threshold=70
# Bottleneck - long window size (type: uint32, unit: second, default: 600)
#    min: 90
#    max: 3600
bottleneck.long.size=600
# Bottleneck - long window threshold (type: uint32, unit: percent, default: 30%)
#    min：0
#    max: 100
bottleneck.long.threshold=30
# Maximum reliable period of borrowing strategy data
strategy.maxReliableTimes=3
# Master main process interval time (s)
master.masterInterval=10
# Maximum borrowed memory, Byte
master.maxBorrowSize=1073741824
