# Authentication configuration file
# Defines base user-role and role-permission mappings with priority flags.

[auth.user]
# Section for user-to-role mappings.
nova=vm_nova
ubs-scheduler=vm_op
matrixplugin=vm_k8s

[auth.role]
# Section for role-to-permission mappings.
vm_nova=vm.migrate,vm.case_conf
vm_op=topo,vm.query,vm.fragmentation,vm.case_conf
vm_k8s=mem.numa,topo,vm.container