# Name of the vm plugin. Fixed value: vm.
ubse.plugin.name=vm
# Name of the SO file on which the vm module depends. Fixed value: libvm.so.
ubse.plugin.pkg=libvm.so
# Collection period of the VM module, in seconds. The value range is [1, 60].Any invalid value will be reset to 2.
ubse.plugin.vm.export.interval=2

# Decision configuration item
# Second escape watermark of the decision-making module. A value greater than the second escape watermark will trigger memory borrowing. The value range is [70, 95](and borrow.watermark >= high.watermark + 5).Any invalid value will be reset to 92.
borrow.watermark=92
# High and low watermark percentage configuration with a value range of [0, 100]. A high watermark triggers borrowing or migration, and a low watermark triggers returning. The value is configured to the memory subsystem and used for decision-making modules.
# [Only for virtualization scenario] High watermark percentage configuration with a value range of [65, 90](and high.watermark >= low.watermark + 5)
# [Only for virtualization scenario] Low watermark percentage configuration with a value range of [60, 80]
high.watermark=85
low.watermark=80

# Maximum borrowed memory of a single block, in MB. The value range is {1024, 2048, 3072, 4096} (enumerated values).Any invalid value will be reset to 4096.
borrow.maxMemPerBorrowSize=4096
# Minimum borrowed memory of a single block, in MB. The value range is {1024, 2048, 3072, 4096} (enumerated values). The value of minMemPerBorrowSize should be less than that of maxMemPerBorrowSize.Any invalid value will be reset to 1024.
borrow.minMemPerBorrowSize=1024
# Maximum memory borrowed each time, in MB. The value range is [4096, 20480] ([4G, 20G]). default 16384 (16G).
borrow.maxPerTotalMemBorrowSize=16384
# oom event borrow mem size, in MB. The value range is [1024, 4096].Any invalid value will be reset to 1024.
borrow.oomBorrowMemSize=1024
# Maximum timeout for single VM ham migration, in seconds. The value range is [10-10800]. Any invalid value will be reset to 60.
mig.ham.maxTimeout=60
# Absolute path of the SO file of the customized escape strategy algorithm. The default value is '/usr/lib64/libstrategy.so'.
escape.algorithm.dir=/usr/lib64/libstrategy.so

# Current environment whether using ham migration.The default value is false.
mig.isEnableHamMigrate=false
# Vm memory bound to get migrate strategy,in MB. The value range is [256, 4096].Any invalid value will be reset to 4096.
mig.migrateOneCopyMemoryBound=4096
# Page type configuration, which is used to set the page unit when the cold memory is migrated out. The value can be 0 or 1. The value 0 indicates the standard page, and the value 1 indicates the 2 MB huge page. The default value is 1.
virt.pageType=1
# Current scenario. The value can be 0 or 1. The value 0 indicates the container scenario, and the value 1 indicates the VM scenario. The default value is 1.
virt.sceneType=1

